#!/bin/bash
MADRONA_TRACE_TEST=0 MADRONA_LOADED_ENV=0 MADRONA_MERGE_ALL=0 MADRONA_TIMING_FILE=timing.txt MADRONA_RENDER_RESOLUTION=1 MADRONA_RENDER_MODE=1 MADRONA_MWGPU_KERNEL_CACHE=cache ./build/viewer 512 --cuda
